# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    pwd 
    ls -ltr 
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'MCAPS-Hybrid-REQ-48872-2022-GaryCiampa (32f5e9a7-8253-4f47-9f6f-8d5a7b8a3477)'
    subscriptionId: '32f5e9a7-8253-4f47-9f6f-8d5a7b8a3477'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'gaciampap1_rg1'
    location: 'East US 2'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/garyciampa/ARMPipeline-repo/main/azuredeploy.json'
    overrideParameters: '-projectName gaciampap1'
    deploymentMode: 'Incremental'
    deploymentName: 'DemoLinkedTemplate'